In [3]:
import pandas as pd

df1 = pd.read_csv('output/raw_econ_rebuild_group1.csv')
cols = ['match_id', 'map_id', 'steam_id']
cols.extend([x for x in df1.columns if x.endswith('_bonus')])

df1 = df1[cols]
df1[df1['match_id'] == 71357]

,match_id,map_id,steam_id,round_end_bonus,rifle_bonus,sniper_bonus,grenade_bonus,lmg_bonus,shotgun_bonus,smg_bonus,pistol_bonus,melee_bonus,awp_bonus,p90_bonus,cz75_bonus,bomb_plant_bonus,team_bomb_explode_bonus,plant_but_lost_bonus,bomb_defuse_bonus,team_bomb_defuse_bonus
107820,71357,71669,76561197962710908,112300,5700,0,300,0,0,0,0,0,0,0,0,0,0,0,0,0
107821,71357,71669,76561197973757802,110650,6900,0,0,0,0,0,600,0,0,0,0,600,500,0,300,250
107822,71357,71669,76561197976197744,112300,6600,0,300,0,0,0,600,0,0,0,0,900,500,800,0,0
107823,71357,71669,76561198013172503,112300,4200,0,300,0,0,0,1200,0,600,0,0,300,0,800,0,0
107824,71357,71669,76561198027609568,110650,5100,0,0,0,0,600,1200,0,0,0,0,0,0,0,0,0
107825,71357,71669,76561198035334871,112300,600,0,300,0,0,0,2400,0,3000,0,0,300,0,800,0,0
107826,71357,71669,76561198065448360,110650,1800,0,0,0,0,0,300,0,1600,0,0,0,0,0,300,250
107827,71357,71669,76561198186878873,110650,8100,0,0,0,0,600,600,0,0,0,0,900,750,0,300,250
107828,71357,71669,76561198258187741,112300,6600,0,300,0,0,0,900,0,0,0,0,600,0,1600,0,0
107829,71357,71669,76561198262460262,110650,5700,0,0,0,0,1800,1200,0,0,0,0,0,0,0,600,500

In [30]:
df1g = df1.groupby(['match_id', 'steam_id']).mean().reset_index()
df1g[df1g['match_id'] == 64104]
df1g = df1g.drop(columns=['map_id'])
df1g.to_csv('output/detailed_econ.csv', index=False)

In [25]:
t = df1.groupby('match_id').count()
t[t['map_id'] == 30]

,map_id,steam_id,round_number,won,rifle_kills,sniper_kills,grenade_kills,lmg_kills,shotgun_kills,smg_kills,...,melee_bonus,awp_bonus,p90_bonus,cz75_bonus,bomb_plant_bonus,team_bomb_explode_bonus,plant_but_lost_bonus,bomb_defuse_bonus,team_bomb_defuse_bonus,total_money_made
match_id,,,,,,,,,,,,,,,,,,,,,
64104,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
64108,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
64111,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
64120,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
64125,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71302,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
71311,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
71324,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
71331,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
71343,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30

In [5]:
df = pd.read_csv('csgo/output/match_money_df.csv')
df.head(11)
# cols = ['match_id', 'steam_id']
# cols.extend([x for x in df.columns if x.endswith('_bonus')])

# df = df[cols]
# df.head(21)

FileNotFoundError: [Errno 2] No such file or directory: 'csgo/output/match_money_df.csv'

In [5]:
import pandas as pd

df = pd.read_csv('output/raw_econ_rebuild.csv')
cols = ['match_id', 'map_id', 'steam_id', 'round_number']
cols.extend([x for x in df1.columns if x.endswith('_bonus')])

df = df[cols]
df.head(21)

,match_id,map_id,steam_id,round_number,round_end_bonus,rifle_bonus,sniper_bonus,grenade_bonus,lmg_bonus,shotgun_bonus,...,pistol_bonus,melee_bonus,awp_bonus,p90_bonus,cz75_bonus,bomb_plant_bonus,team_bomb_explode_bonus,plant_but_lost_bonus,bomb_defuse_bonus,team_bomb_defuse_bonus
0,0,2,76561197960710573,1,3250,0,0,0,0,0,...,300,0,0,0,0,0,0,0,0,0
1,0,2,76561197960710573,2,3250,600,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,2,76561197960710573,3,3250,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,2,76561197960710573,4,3250,300,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,2,76561197960710573,5,1500,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,2,76561197960710573,6,2000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,2,76561197960710573,7,3250,0,0,0,0,0,...,600,0,0,0,0,0,0,0,0,0
7,0,2,76561197960710573,8,3250,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,2,76561197960710573,9,3250,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,2,76561197960710573,10,1500,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,2,76561197960710573,11,3250,600,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,2,76561197960710573,12,3250,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,2,76561197960710573,13,1500,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,2,76561197960710573,14,2000,0,0,0,0,0,...,300,0,0,0,0,0,0,0,0,0
14,0,2,76561197960710573,15,3250,0,0,0,0,0,...,300,0,0,0,0,0,0,0,0,0
15,0,2,76561197960710573,16,3250,0,0,0,0,0,...,1200,0,0,0,0,0,0,0,0,0
16,0,2,76561197960710573,17,3250,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,2,76561197960710573,18,3250,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,2,76561197960710573,19,3250,0,0,0,0,0,...,0,0,0,0,0,300,250,0,0,0
19,0,2,76561197960710573,20,1500,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,2,76561197960710573,21,2000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [1]:
import pandas as pd

df = pd.read_csv('games/csgo/output/buy_quality.csv')
df.head(21)

,Unnamed: 0,round_number,steam_id,primary_weapon_id,side,has_helmet,armor,has_defuse,starting_flashes,starting_incendiary,starting_smoke,starting_he,starting_decoy,round_spend,full_buy
0,0,6,76561197969744810,0,T,False,100,False,0,0,1,0,0,1300,0
1,1,6,76561197981849043,0,T,False,100,False,1,0,1,0,0,1500,0
2,2,6,76561198032999467,303,CT,False,100,False,1,1,1,1,0,5100,2
3,3,6,76561198063568627,0,T,False,0,False,0,0,0,0,0,0,0
4,4,6,76561198124141035,303,CT,False,100,False,1,1,1,0,0,4800,1
5,5,6,76561198153580037,309,CT,False,100,False,0,1,1,1,0,6950,2
6,6,6,76561198157421038,0,T,False,0,False,0,0,0,0,0,0,0
7,7,6,76561198171719689,305,CT,False,100,False,1,1,1,1,0,5300,2
8,8,6,76561198232522208,0,T,False,100,False,1,0,0,0,0,1200,0
9,9,6,76561198233075160,305,CT,False,100,False,1,1,1,1,0,5300,2
10,10,28,76561197969744810,303,T,False,100,False,1,0,1,1,0,4500,2
11,11,28,76561197981849043,309,T,False,100,False,1,0,1,1,0,6550,2
12,12,28,76561198032999467,0,CT,False,100,False,1,2,1,1,0,3000,1
13,13,28,76561198063568627,303,T,False,100,False,1,1,1,0,0,4600,2
14,14,28,76561198124141035,305,CT,False,100,False,1,1,1,0,0,5000,1
15,15,28,76561198153580037,309,CT,False,100,False,1,1,1,1,0,7150,2
16,16,28,76561198157421038,303,T,False,100,False,1,1,1,1,0,4900,2
17,17,28,76561198171719689,305,CT,False,100,False,1,1,1,1,0,5300,2
18,18,28,76561198232522208,303,T,False,100,False,1,0,1,0,0,4200,1
19,19,28,76561198233075160,305,CT,False,100,False,1,1,1,1,0,5300,2
20,20,6,76561197963504595,305,CT,False,100,False,0,1,0,0,0,4500,1

In [9]:
import os
os.getcwd()

'/home/matias/Projects/model_notebooks/games/csgo'